<option vlaue="Adilabad">Adilabad</option>
<option vlaue="Agra">Agra</option>
<option vlaue="Ahmedabad">Ahmedabad</option>
<option vlaue="Ahmednagar">Ahmednagar</option>
<option vlaue="Aizawl">Aizawl</option>
<option vlaue="Ajitgarh_(Mohali)">Ajitgarh (Mohali)</option>
<option vlaue="Ajmer">Ajmer</option>
<option vlaue="Akola">Akola</option>
<option vlaue="Alappuzha">Alappuzha</option>
<option vlaue="Aligarh">Aligarh</option>
<option vlaue="Alirajpur">Alirajpur</option>
<option vlaue="Allahabad">Allahabad</option>
<option vlaue="Almora">Almora</option>
<option vlaue="Alwar">Alwar</option>
<option vlaue="Ambala">Ambala</option>
<option vlaue="Ambedkar_Nagar">Ambedkar Nagar</option>
<option vlaue="Amravati">Amravati</option>
<option vlaue="Amreli_district">Amreli district</option>
<option vlaue="Amritsar">Amritsar</option>
<option vlaue="Anand">Anand</option>
<option vlaue="Anantapur">Anantapur</option>
<option vlaue="Anantnag">Anantnag</option>
<option vlaue="Angul">Angul</option>
<option vlaue="Anjaw">Anjaw</option>
<option vlaue="Anuppur">Anuppur</option>
<option vlaue="Araria">Araria</option>
<option vlaue="Ariyalur">Ariyalur</option>
<option vlaue="Arwal">Arwal</option>
<option vlaue="Ashok_Nagar">Ashok Nagar</option>
<option vlaue="Auraiya">Auraiya</option>
<option vlaue="Aurangabad">Aurangabad</option>
<option vlaue="Aurangabad">Aurangabad</option>
<option vlaue="Azamgarh">Azamgarh</option>
<option vlaue="Badgam">Badgam</option>
<option vlaue="Bagalkot">Bagalkot</option>
<option vlaue="Bageshwar">Bageshwar</option>
<option vlaue="Bagpat">Bagpat</option>
<option vlaue="Bahraich">Bahraich</option>
<option vlaue="Baksa">Baksa</option>
<option vlaue="Balaghat">Balaghat</option>
<option vlaue="Balangir">Balangir</option>
<option vlaue="Balasore">Balasore</option>
<option vlaue="Ballia">Ballia</option>
<option vlaue="Balrampur">Balrampur</option>
<option vlaue="Banaskantha">Banaskantha</option>
<option vlaue="Banda">Banda</option>
<option vlaue="Bandipora">Bandipora</option>
<option vlaue="Bangalore_Rural">Bangalore Rural</option>
<option vlaue="Bangalore_Urban">Bangalore Urban</option>
<option vlaue="Banka">Banka</option>
<option vlaue="Bankura">Bankura</option>
<option vlaue="Banswara">Banswara</option>
<option vlaue="Barabanki">Barabanki</option>
<option vlaue="Baramulla">Baramulla</option>
<option vlaue="Baran">Baran</option>
<option vlaue="Bardhaman">Bardhaman</option>
<option vlaue="Bareilly">Bareilly</option>
<option vlaue="Bargarh_(Baragarh)">Bargarh (Baragarh)</option>
<option vlaue="Barmer">Barmer</option>
<option vlaue="Barnala">Barnala</option>
<option vlaue="Barpeta">Barpeta</option>
<option vlaue="Barwani">Barwani</option>
<option vlaue="Bastar">Bastar</option>
<option vlaue="Basti">Basti</option>
<option vlaue="Bathinda">Bathinda</option>
<option vlaue="Beed">Beed</option>
<option vlaue="Begusarai">Begusarai</option>
<option vlaue="Belgaum">Belgaum</option>
<option vlaue="Bellary">Bellary</option>
<option vlaue="Betul">Betul</option>
<option vlaue="Bhadrak">Bhadrak</option>
<option vlaue="Bhagalpur">Bhagalpur</option>
<option vlaue="Bhandara">Bhandara</option>
<option vlaue="Bharatpur">Bharatpur</option>
<option vlaue="Bharuch">Bharuch</option>
<option vlaue="Bhavnagar">Bhavnagar</option>
<option vlaue="Bhilwara">Bhilwara</option>
<option vlaue="Bhind">Bhind</option>
<option vlaue="Bhiwani">Bhiwani</option>
<option vlaue="Bhojpur">Bhojpur</option>
<option vlaue="Bhopal">Bhopal</option>
<option vlaue="Bidar">Bidar</option>
<option vlaue="Bijapur">Bijapur</option>
<option vlaue="Bijapur">Bijapur</option>
<option vlaue="Bijnor">Bijnor</option>
<option vlaue="Bikaner">Bikaner</option>
<option vlaue="Bilaspur">Bilaspur</option>
<option vlaue="Bilaspur">Bilaspur</option>
<option vlaue="Birbhum">Birbhum</option>
<option vlaue="Bishnupur">Bishnupur</option>
<option vlaue="Bokaro">Bokaro</option>
<option vlaue="Bongaigaon">Bongaigaon</option>
<option vlaue="Boudh_Bauda">Boudh (Bauda)</option>
<option vlaue="Budaun">Budaun</option>
<option vlaue="Bulandshahr">Bulandshahr</option>
<option vlaue="Buldhana">Buldhana</option>
<option vlaue="Bundi">Bundi</option>
<option vlaue="Burhanpur">Burhanpur</option>
<option vlaue="Buxar">Buxar</option>
<option vlaue="Cachar">Cachar</option>
<option vlaue="Central_Delhi">Central Delhi</option>
<option vlaue="Chamarajnagar">Chamarajnagar</option>
<option vlaue="Chamba">Chamba</option>
<option vlaue="Chamoli">Chamoli</option>
<option vlaue="Champawat">Champawat</option>
<option vlaue="Champhai">Champhai</option>
<option vlaue="Chandauli">Chandauli</option>
<option vlaue="Chandel">Chandel</option>
<option vlaue="Chandigarh">Chandigarh</option>
<option vlaue="Chandrapur">Chandrapur</option>
<option vlaue="Changlang">Changlang</option>
<option vlaue="Chatra">Chatra</option>
<option vlaue="Chennai">Chennai</option>
<option vlaue="Chhatarpur">Chhatarpur</option>
<option vlaue="Chhatrapati_Shahuji_Maharaj_Nagar">Chhatrapati Shahuji Maharaj Nagar</option>
<option vlaue="Chhindwara">Chhindwara</option>
<option vlaue="Chikkaballapur">Chikkaballapur</option>
<option vlaue="Chikkamagaluru">Chikkamagaluru</option>
<option vlaue="Chirang">Chirang</option>
<option vlaue="Chitradurga">Chitradurga</option>
<option vlaue="Chitrakoot">Chitrakoot</option>
<option vlaue="Chittoor">Chittoor</option>
<option vlaue="Chittorgarh">Chittorgarh</option>
<option vlaue="Churachandpur">Churachandpur</option>
<option vlaue="Churu">Churu</option>
<option vlaue="Coimbatore">Coimbatore</option>
<option vlaue="Cooch Behar">Cooch Behar</option>
<option vlaue="Cuddalore">Cuddalore</option>
<option vlaue="Cuttack">Cuttack</option>
<option vlaue="Dadra and Nagar Haveli">Dadra and Nagar Haveli</option>
<option vlaue="Dahod">Dahod</option>
<option vlaue="Dakshin Dinajpur">Dakshin Dinajpur</option>
<option vlaue="Dakshina Kannada">Dakshina Kannada</option>
<option vlaue="Daman">Daman</option>
<option vlaue="Damoh">Damoh</option>
<option vlaue="Dantewada">Dantewada</option>
<option vlaue="Darbhanga">Darbhanga</option>
<option vlaue="Darjeeling">Darjeeling</option>
<option vlaue="Darrang">Darrang</option>
<option vlaue="Datia">Datia</option>
<option vlaue="Dausa">Dausa</option>
<option vlaue="Davanagere">Davanagere</option>
<option vlaue="Debagarh (Deogarh)">Debagarh (Deogarh)</option>
<option vlaue="Dehradun">Dehradun</option>
<option vlaue="Deoghar">Deoghar</option>
<option vlaue="Deoria">Deoria</option>
<option vlaue="Dewas">Dewas</option>
<option vlaue="Dhalai">Dhalai</option>
<option vlaue="Dhamtari">Dhamtari</option>
<option vlaue="Dhanbad">Dhanbad</option>
<option vlaue="Dhar">Dhar</option>
<option vlaue="Dharmapuri">Dharmapuri</option>
<option vlaue="Dharwad">Dharwad</option>
<option vlaue="Dhemaji">Dhemaji</option>
<option vlaue="Dhenkanal">Dhenkanal</option>
<option vlaue="Dholpur">Dholpur</option>
<option vlaue="Dhubri">Dhubri</option>
<option vlaue="Dhule">Dhule</option>
<option vlaue="Dibang Valley">Dibang Valley</option>
<option vlaue="Dibrugarh">Dibrugarh</option>
<option vlaue="Dima Hasao">Dima Hasao</option>
<option vlaue="Dimapur">Dimapur</option>
<option vlaue="Dindigul">Dindigul</option>
<option vlaue="Dindori">Dindori</option>
<option vlaue="Diu">Diu</option>
<option vlaue="Doda">Doda</option>
<option vlaue="Dumka">Dumka</option>
<option vlaue="Dungapur">Dungapur</option>
<option vlaue="Durg">Durg</option>
<option vlaue="East Champaran">East Champaran</option>
<option vlaue="East Delhi">East Delhi</option>
<option vlaue="East Garo Hills">East Garo Hills</option>
<option vlaue="East Khasi Hills">East Khasi Hills</option>
<option vlaue="East Siang">East Siang</option>
<option vlaue="East Sikkim">East Sikkim</option>
<option vlaue="East Singhbhum">East Singhbhum</option>
<option vlaue="Eluru">Eluru</option>
<option vlaue="Ernakulam">Ernakulam</option>
<option vlaue="Erode">Erode</option>
<option vlaue="Etah">Etah</option>
<option vlaue="Etawah">Etawah</option>
<option vlaue="Faizabad">Faizabad</option>
<option vlaue="Faridabad">Faridabad</option>
<option vlaue="Faridkot">Faridkot</option>
<option vlaue="Farrukhabad">Farrukhabad</option>
<option vlaue="Fatehabad">Fatehabad</option>
<option vlaue="Fatehgarh Sahib">Fatehgarh Sahib</option>
<option vlaue="Fatehpur">Fatehpur</option>
<option vlaue="Fazilka">Fazilka</option>
<option vlaue="Firozabad">Firozabad</option>
<option vlaue="Firozpur">Firozpur</option>
<option vlaue="Gadag">Gadag</option>
<option vlaue="Gadchiroli">Gadchiroli</option>
<option vlaue="Gajapati">Gajapati</option>
<option vlaue="Ganderbal">Ganderbal</option>
<option vlaue="Gandhinagar">Gandhinagar</option>
<option vlaue="Ganganagar">Ganganagar</option>
<option vlaue="Ganjam">Ganjam</option>
<option vlaue="Garhwa">Garhwa</option>
<option vlaue="Gautam Buddh Nagar">Gautam Buddh Nagar</option>
<option vlaue="Gaya">Gaya</option>
<option vlaue="Ghaziabad">Ghaziabad</option>
<option vlaue="Ghazipur">Ghazipur</option>
<option vlaue="Giridih">Giridih</option>
<option vlaue="Goalpara">Goalpara</option>
<option vlaue="Godda">Godda</option>
<option vlaue="Golaghat">Golaghat</option>
<option vlaue="Gonda">Gonda</option>
<option vlaue="Gondia">Gondia</option>
<option vlaue="Gopalganj">Gopalganj</option>
<option vlaue="Gorakhpur">Gorakhpur</option>
<option vlaue="Gulbarga">Gulbarga</option>
<option vlaue="Gumla">Gumla</option>
<option vlaue="Guna">Guna</option>
<option vlaue="Guntur">Guntur</option>
<option vlaue="Gurdaspur">Gurdaspur</option>
<option vlaue="Gurgaon">Gurgaon</option>
<option vlaue="Gwalior">Gwalior</option>
<option vlaue="Hailakandi">Hailakandi</option>
<option vlaue="Hamirpur">Hamirpur</option>
<option vlaue="Hamirpur">Hamirpur</option>
<option vlaue="Hanumangarh">Hanumangarh</option>
<option vlaue="Harda">Harda</option>
<option vlaue="Hardoi">Hardoi</option>
<option vlaue="Haridwar">Haridwar</option>
<option vlaue="Hassan">Hassan</option>
<option vlaue="Haveri district">Haveri district</option>
<option vlaue="Hazaribag">Hazaribag</option>
<option vlaue="Hingoli">Hingoli</option>
<option vlaue="Hissar">Hissar</option>
<option vlaue="Hooghly">Hooghly</option>
<option vlaue="Hoshangabad">Hoshangabad</option>
<option vlaue="Hoshiarpur">Hoshiarpur</option>
<option vlaue="Howrah">Howrah</option>
<option vlaue="Hyderabad">Hyderabad</option>
<option vlaue="Hyderabad">Hyderabad</option>
<option vlaue="Idukki">Idukki</option>
<option vlaue="Imphal East">Imphal East</option>
<option vlaue="Imphal West">Imphal West</option>
<option vlaue="Indore">Indore</option>
<option vlaue="Jabalpur">Jabalpur</option>
<option vlaue="Jagatsinghpur">Jagatsinghpur</option>
<option vlaue="Jaintia Hills">Jaintia Hills</option>
<option vlaue="Jaipur">Jaipur</option>
<option vlaue="Jaisalmer">Jaisalmer</option>
<option vlaue="Jajpur">Jajpur</option>
<option vlaue="Jalandhar">Jalandhar</option>
<option vlaue="Jalaun">Jalaun</option>
<option vlaue="Jalgaon">Jalgaon</option>
<option vlaue="Jalna">Jalna</option>
<option vlaue="Jalore">Jalore</option>
<option vlaue="Jalpaiguri">Jalpaiguri</option>
<option vlaue="Jammu">Jammu</option>
<option vlaue="Jamnagar">Jamnagar</option>
<option vlaue="Jamtara">Jamtara</option>
<option vlaue="Jamui">Jamui</option>
<option vlaue="Janjgir-Champa">Janjgir-Champa</option>
<option vlaue="Jashpur">Jashpur</option>
<option vlaue="Jaunpur district">Jaunpur district</option>
<option vlaue="Jehanabad">Jehanabad</option>
<option vlaue="Jhabua">Jhabua</option>
<option vlaue="Jhajjar">Jhajjar</option>
<option vlaue="Jhalawar">Jhalawar</option>
<option vlaue="Jhansi">Jhansi</option>
<option vlaue="Jharsuguda">Jharsuguda</option>
<option vlaue="Jhunjhunu">Jhunjhunu</option>
<option vlaue="Jind">Jind</option>
<option vlaue="Jodhpur">Jodhpur</option>
<option vlaue="Jorhat">Jorhat</option>
<option vlaue="Junagadh">Junagadh</option>
<option vlaue="Jyotiba Phule Nagar">Jyotiba Phule Nagar</option>
<option vlaue="Kabirdham (formerly Kawardha)">Kabirdham (formerly Kawardha)</option>
<option vlaue="Kadapa">Kadapa</option>
<option vlaue="Kaimur">Kaimur</option>
<option vlaue="Kaithal">Kaithal</option>
<option vlaue="Kakinada">Kakinada</option>
<option vlaue="Kalahandi">Kalahandi</option>
<option vlaue="Kamrup">Kamrup</option>
<option vlaue="Kamrup Metropolitan">Kamrup Metropolitan</option>
<option vlaue="Kanchipuram">Kanchipuram</option>
<option vlaue="Kandhamal">Kandhamal</option>
<option vlaue="Kangra">Kangra</option>
<option vlaue="Kanker">Kanker</option>
<option vlaue="Kannauj">Kannauj</option>
<option vlaue="Kannur">Kannur</option>
<option vlaue="Kanpur">Kanpur</option>
<option vlaue="Kanshi Ram Nagar">Kanshi Ram Nagar</option>
<option vlaue="Kanyakumari">Kanyakumari</option>
<option vlaue="Kapurthala">Kapurthala</option>
<option vlaue="Karaikal">Karaikal</option>
<option vlaue="Karauli">Karauli</option>
<option vlaue="Karbi Anglong">Karbi Anglong</option>
<option vlaue="Kargil">Kargil</option>
<option vlaue="Karimganj">Karimganj</option>
<option vlaue="Karimnagar">Karimnagar</option>
<option vlaue="Karnal">Karnal</option>
<option vlaue="Karur">Karur</option>
<option vlaue="Kasaragod">Kasaragod</option>
<option vlaue="Kathua">Kathua</option>
<option vlaue="Katihar">Katihar</option>
<option vlaue="Katni">Katni</option>
<option vlaue="Kaushambi">Kaushambi</option>
<option vlaue="Kendrapara">Kendrapara</option>
<option vlaue="Kendujhar (Keonjhar)">Kendujhar (Keonjhar)</option>
<option vlaue="Khagaria">Khagaria</option>
<option vlaue="Khammam">Khammam</option>
<option vlaue="Khandwa (East Nimar)">Khandwa (East Nimar)</option>
<option vlaue="Khargone (West Nimar)">Khargone (West Nimar)</option>
<option vlaue="Kheda">Kheda</option>
<option vlaue="Khordha">Khordha</option>
<option vlaue="Khowai">Khowai</option>
<option vlaue="Khunti">Khunti</option>
<option vlaue="Kinnaur">Kinnaur</option>
<option vlaue="Kishanganj">Kishanganj</option>
<option vlaue="Kishtwar">Kishtwar</option>
<option vlaue="Kodagu">Kodagu</option>
<option vlaue="Koderma">Koderma</option>
<option vlaue="Kohima">Kohima</option>
<option vlaue="Kokrajhar">Kokrajhar</option>
<option vlaue="Kolar">Kolar</option>
<option vlaue="Kolasib">Kolasib</option>
<option vlaue="Kolhapur">Kolhapur</option>
<option vlaue="Kolkata">Kolkata</option>
<option vlaue="Kollam">Kollam</option>
<option vlaue="Koppal">Koppal</option>
<option vlaue="Koraput">Koraput</option>
<option vlaue="Korba">Korba</option>
<option vlaue="Koriya">Koriya</option>
<option vlaue="Kota">Kota</option>
<option vlaue="Kottayam">Kottayam</option>
<option vlaue="Kozhikode">Kozhikode</option>
<option vlaue="Krishna">Krishna</option>
<option vlaue="Kulgam">Kulgam</option>
<option vlaue="Kullu">Kullu</option>
<option vlaue="Kupwara">Kupwara</option>
<option vlaue="Kurnool">Kurnool</option>
<option vlaue="Kurukshetra">Kurukshetra</option>
<option vlaue="Kurung Kumey">Kurung Kumey</option>
<option vlaue="Kushinagar">Kushinagar</option>
<option vlaue="Kutch">Kutch</option>
<option vlaue="Lahaul and Spiti">Lahaul and Spiti</option>
<option vlaue="Lakhimpur">Lakhimpur</option>
<option vlaue="Lakhimpur Kheri">Lakhimpur Kheri</option>
<option vlaue="Lakhisarai">Lakhisarai</option>
<option vlaue="Lalitpur">Lalitpur</option>
<option vlaue="Latehar">Latehar</option>
<option vlaue="Latur">Latur</option>
<option vlaue="Lawngtlai">Lawngtlai</option>
<option vlaue="Leh">Leh</option>
<option vlaue="Lohardaga">Lohardaga</option>
<option vlaue="Lohit">Lohit</option>
<option vlaue="Lower Dibang Valley">Lower Dibang Valley</option>
<option vlaue="Lower Subansiri">Lower Subansiri</option>
<option vlaue="Lucknow">Lucknow</option>
<option vlaue="Ludhiana">Ludhiana</option>
<option vlaue="Lunglei">Lunglei</option>
<option vlaue="Madhepura">Madhepura</option>
<option vlaue="Madhubani">Madhubani</option>
<option vlaue="Madurai">Madurai</option>
<option vlaue="Mahamaya Nagar">Mahamaya Nagar</option>
<option vlaue="Maharajganj">Maharajganj</option>
<option vlaue="Mahasamund">Mahasamund</option>
<option vlaue="Mahbubnagar">Mahbubnagar</option>
<option vlaue="Mahe">Mahe</option>
<option vlaue="Mahendragarh">Mahendragarh</option>
<option vlaue="Mahoba">Mahoba</option>
<option vlaue="Mainpuri">Mainpuri</option>
<option vlaue="Malappuram">Malappuram</option>
<option vlaue="Maldah">Maldah</option>
<option vlaue="Malkangiri">Malkangiri</option>
<option vlaue="Mamit">Mamit</option>
<option vlaue="Mandi">Mandi</option>
<option vlaue="Mandla">Mandla</option>
<option vlaue="Mandsaur">Mandsaur</option>
<option vlaue="Mandya">Mandya</option>
<option vlaue="Mansa">Mansa</option>
<option vlaue="Marigaon">Marigaon</option>
<option vlaue="Mathura">Mathura</option>
<option vlaue="Mau">Mau</option>
<option vlaue="Mayurbhanj">Mayurbhanj</option>
<option vlaue="Medak">Medak</option>
<option vlaue="Meerut">Meerut</option>
<option vlaue="Mehsana">Mehsana</option>
<option vlaue="Mewat">Mewat</option>
<option vlaue="Mirzapur">Mirzapur</option>
<option vlaue="Moga">Moga</option>
<option vlaue="Mokokchung">Mokokchung</option>
<option vlaue="Mon">Mon</option>
<option vlaue="Moradabad">Moradabad</option>
<option vlaue="Morena">Morena</option>
<option vlaue="Mumbai City">Mumbai City</option>
<option vlaue="Mumbai suburban">Mumbai suburban</option>
<option vlaue="Munger">Munger</option>
<option vlaue="Murshidabad">Murshidabad</option>
<option vlaue="Muzaffarnagar">Muzaffarnagar</option>
<option vlaue="Muzaffarpur">Muzaffarpur</option>
<option vlaue="Mysore">Mysore</option>
<option vlaue="Nabarangpur">Nabarangpur</option>
<option vlaue="Nadia">Nadia</option>
<option vlaue="Nagaon">Nagaon</option>
<option vlaue="Nagapattinam">Nagapattinam</option>
<option vlaue="Nagaur">Nagaur</option>
<option vlaue="Nagpur">Nagpur</option>
<option vlaue="Nainital">Nainital</option>
<option vlaue="Nalanda">Nalanda</option>
<option vlaue="Nalbari">Nalbari</option>
<option vlaue="Nalgonda">Nalgonda</option>
<option vlaue="Namakkal">Namakkal</option>
<option vlaue="Nanded">Nanded</option>
<option vlaue="Nandurbar">Nandurbar</option>
<option vlaue="Narayanpur">Narayanpur</option>
<option vlaue="Narmada">Narmada</option>
<option vlaue="Narsinghpur">Narsinghpur</option>
<option vlaue="Nashik">Nashik</option>
<option vlaue="Navsari">Navsari</option>
<option vlaue="Nawada">Nawada</option>
<option vlaue="Nawanshahr">Nawanshahr</option>
<option vlaue="Nayagarh">Nayagarh</option>
<option vlaue="Neemuch">Neemuch</option>
<option vlaue="Nellore">Nellore</option>
<option vlaue="New Delhi">New Delhi</option>
<option vlaue="Nilgiris">Nilgiris</option>
<option vlaue="Nizamabad">Nizamabad</option>
<option vlaue="North 24 Parganas">North 24 Parganas</option>
<option vlaue="North Delhi">North Delhi</option>
<option vlaue="North East Delhi">North East Delhi</option>
<option vlaue="North Goa">North Goa</option>
<option vlaue="North Sikkim">North Sikkim</option>
<option vlaue="North Tripura">North Tripura</option>
<option vlaue="North West Delhi">North West Delhi</option>
<option vlaue="Nuapada">Nuapada</option>
<option vlaue="Ongole">Ongole</option>
<option vlaue="Osmanabad">Osmanabad</option>
<option vlaue="Pakur">Pakur</option>
<option vlaue="Palakkad">Palakkad</option>
<option vlaue="Palamu">Palamu</option>
<option vlaue="Pali">Pali</option>
<option vlaue="Palwal">Palwal</option>
<option vlaue="Panchkula">Panchkula</option>
<option vlaue="Panchmahal">Panchmahal</option>
<option vlaue="Panchsheel Nagar district (Hapur)">Panchsheel Nagar district (Hapur)</option>
<option vlaue="Panipat">Panipat</option>
<option vlaue="Panna">Panna</option>
<option vlaue="Papum Pare">Papum Pare</option>
<option vlaue="Parbhani">Parbhani</option>
<option vlaue="Paschim_Medinipur">Paschim Medinipur</option>
<option vlaue="Patan">Patan</option>
<option vlaue="Pathanamthitta">Pathanamthitta</option>
<option vlaue="Pathankot">Pathankot</option>
<option vlaue="Patiala">Patiala</option>
<option vlaue="Patna">Patna</option>
<option vlaue="Pauri Garhwal">Pauri Garhwal</option>
<option vlaue="Perambalur">Perambalur</option>
<option vlaue="Phek">Phek</option>
<option vlaue="Pilibhit">Pilibhit</option>
<option vlaue="Pithoragarh">Pithoragarh</option>
<option vlaue="Pondicherry">Pondicherry</option>
<option vlaue="Poonch">Poonch</option>
<option vlaue="Porbandar">Porbandar</option>
<option vlaue="Pratapgarh">Pratapgarh</option>
<option vlaue="Pratapgarh">Pratapgarh</option>
<option vlaue="Pudukkottai">Pudukkottai</option>
<option vlaue="Pulwama">Pulwama</option>
<option vlaue="Pune">Pune</option>
<option vlaue="Purba Medinipur">Purba Medinipur</option>
<option vlaue="Puri">Puri</option>
<option vlaue="Purnia">Purnia</option>
<option vlaue="Purulia">Purulia</option>
<option vlaue="Raebareli">Raebareli</option>
<option vlaue="Raichur">Raichur</option>
<option vlaue="Raigad">Raigad</option>
<option vlaue="Raigarh">Raigarh</option>
<option vlaue="Raipur">Raipur</option>
<option vlaue="Raisen">Raisen</option>
<option vlaue="Rajauri">Rajauri</option>
<option vlaue="Rajgarh">Rajgarh</option>
<option vlaue="Rajkot">Rajkot</option>
<option vlaue="Rajnandgaon">Rajnandgaon</option>
<option vlaue="Rajsamand">Rajsamand</option>
<option vlaue="Ramabai_Nagar_Kanpur_Dehat)">Ramabai Nagar (Kanpur Dehat)</option>
<option vlaue="Ramanagara">Ramanagara</option>
<option vlaue="Ramanathapuram">Ramanathapuram</option>
<option vlaue="Ramban">Ramban</option>
<option vlaue="Ramgarh">Ramgarh</option>
<option vlaue="Rampur">Rampur</option>
<option vlaue="Ranchi">Ranchi</option>
<option vlaue="Ratlam">Ratlam</option>
<option vlaue="Ratnagiri">Ratnagiri</option>
<option vlaue="Rayagada">Rayagada</option>
<option vlaue="Reasi">Reasi</option>
<option vlaue="Rewa">Rewa</option>
<option vlaue="Rewari">Rewari</option>
<option vlaue="Ri_Bhoi">Ri Bhoi</option>
<option vlaue="Rohtak">Rohtak</option>
<option vlaue="Rohtas">Rohtas</option>
<option vlaue="Rudraprayag">Rudraprayag</option>
<option vlaue="Rupnagar">Rupnagar</option>
<option vlaue="Sabarkantha">Sabarkantha</option>
<option vlaue="Sagar">Sagar</option>
<option vlaue="Saharanpur">Saharanpur</option>
<option vlaue="Saharsa">Saharsa</option>
<option vlaue="Sahibganj">Sahibganj</option>
<option vlaue="Saiha">Saiha</option>
<option vlaue="Salem">Salem</option>
<option vlaue="Samastipur">Samastipur</option>
<option vlaue="Samba">Samba</option>
<option vlaue="Sambalpur">Sambalpur</option>
<option vlaue="Sangli">Sangli</option>
<option vlaue="Sangrur">Sangrur</option>
<option vlaue="Sant_Kabir_Nagar">Sant Kabir Nagar</option>
<option vlaue="Sant_Ravidas_Nagar">Sant Ravidas Nagar</option>
<option vlaue="Saran">Saran</option>
<option vlaue="Satara">Satara</option>
<option vlaue="Satna">Satna</option>
<option vlaue="Sawai_Madhopur">Sawai Madhopur</option>
<option vlaue="Sehore">Sehore</option>
<option vlaue="Senapati">Senapati</option>
<option vlaue="Seoni">Seoni</option>
<option vlaue="Seraikela_Kharsawan">Seraikela Kharsawan</option>
<option vlaue="Serchhip">Serchhip</option>
<option vlaue="Shahdol">Shahdol</option>
<option vlaue="Shahjahanpur">Shahjahanpur</option>
<option vlaue="Shajapur">Shajapur</option>
<option vlaue="Shamli">Shamli</option>
<option vlaue="Sheikhpura">Sheikhpura</option>
<option vlaue="Sheohar">Sheohar</option>
<option vlaue="Sheopur">Sheopur</option>
<option vlaue="Shimla">Shimla</option>
<option vlaue="Shimoga">Shimoga</option>
<option vlaue="Shivpuri">Shivpuri</option>
<option vlaue="Shopian">Shopian</option>
<option vlaue="Shravasti">Shravasti</option>
<option vlaue="Sibsagar">Sibsagar</option>
<option vlaue="Siddharthnagar">Siddharthnagar</option>
<option vlaue="Sidhi">Sidhi</option>
<option vlaue="Sikar">Sikar</option>
<option vlaue="Simdega">Simdega</option>
<option vlaue="Sindhudurg">Sindhudurg</option>
<option vlaue="Singrauli">Singrauli</option>
<option vlaue="Sirmaur">Sirmaur</option>
<option vlaue="Sirohi">Sirohi</option>
<option vlaue="Sirsa">Sirsa</option>
<option vlaue="Sitamarhi">Sitamarhi</option>
<option vlaue="Sitapur">Sitapur</option>
<option vlaue="Sivaganga">Sivaganga</option>
<option vlaue="Siwan">Siwan</option>
<option vlaue="Solan">Solan</option>
<option vlaue="Solapur">Solapur</option>
<option vlaue="Sonbhadra">Sonbhadra</option>
<option vlaue="Sonipat">Sonipat</option>
<option vlaue="Sonitpur">Sonitpur</option>
<option vlaue="South_24_Parganas">South 24 Parganas</option>
<option vlaue="South_Delhi">South Delhi</option>
<option vlaue="South_Garo_Hills">South Garo Hills</option>
<option vlaue="South_Goa">South Goa</option>
<option vlaue="South_Sikkim">South Sikkim</option>
<option vlaue="South_Tripura">South Tripura</option>
<option vlaue="South_West_Delhi">South West Delhi</option>
<option vlaue="SriMuktsarSahib">Sri Muktsar Sahib</option>
<option vlaue="Srikakulam">Srikakulam</option>
<option vlaue="Srinagar">Srinagar</option>
<option vlaue="Subarnapur_Sonepur">Subarnapur (Sonepur)</option>
<option vlaue="Sultanpur">Sultanpur</option>
<option vlaue="Sundergarh">Sundergarh</option>
<option vlaue="Supaul">Supaul</option>
<option vlaue="Surat">Surat</option>
<option vlaue="Surendranagar">Surendranagar</option>
<option vlaue="Surguja">Surguja</option>
<option vlaue="Tamenglong">Tamenglong</option>
<option vlaue="Tarn_Taran">Tarn Taran</option>
<option vlaue="Tawang">Tawang</option>
<option vlaue="Tehri_Garhwal">Tehri Garhwal</option>
<option vlaue="Thane">Thane</option>
<option vlaue="Thanjavur">Thanjavur</option>
<option vlaue="The_Dangs">The Dangs</option>
<option vlaue="Theni">Theni</option>
<option vlaue="Thiruvananthapuram">Thiruvananthapuram</option>
<option vlaue="Thoothukudi">Thoothukudi</option>
<option vlaue="Thoubal">Thoubal</option>
<option vlaue="Thrissur">Thrissur</option>
<option vlaue="Tikamgarh">Tikamgarh</option>
<option vlaue="Tinsukia">Tinsukia</option>
<option vlaue="Tirap">Tirap</option>
<option vlaue="Tiruchirappalli">Tiruchirappalli</option>
<option vlaue="Tirunelveli">Tirunelveli</option>
<option vlaue="Tirupur">Tirupur</option>
<option vlaue="Tiruvallur">Tiruvallur</option>
<option vlaue="Tiruvannamalai">Tiruvannamalai</option>
<option vlaue="Tiruvarur">Tiruvarur</option>
<option vlaue="Tonk">Tonk</option>
<option vlaue="Tuensang">Tuensang</option>
<option vlaue="Tumkur">Tumkur</option>
<option vlaue="Udaipur">Udaipur</option>
<option vlaue="Udalguri">Udalguri</option>
<option vlaue="Udham_Singh_Nagar">Udham Singh Nagar</option>
<option vlaue="Udhampur">Udhampur</option>
<option vlaue="Udupi">Udupi</option>
<option vlaue="Ujjain">Ujjain</option>
<option vlaue="Ukhrul">Ukhrul</option>
<option vlaue="Umaria">Umaria</option>
<option vlaue="Una">Una</option>
<option vlaue="Unnao">Unnao</option>
<option vlaue="UpperSiang">Upper Siang</option>
<option vlaue="UpperSubansiri">Upper Subansiri</option>
<option vlaue="UttarDinajpur">Uttar Dinajpur</option>
<option vlaue="UttaraKannada">Uttara Kannada</option>
<option vlaue="Uttarkashi">Uttarkashi</option>
<option vlaue="Vadodara">Vadodara</option>
<option vlaue="Vaishali">Vaishali</option>
<option vlaue="Valsad">Valsad</option>
<option vlaue="Varanasi">Varanasi</option>
<option vlaue="Vellore">Vellore</option>
<option vlaue="Vidisha">Vidisha</option>
<option vlaue="Viluppuram">Viluppuram</option>
<option vlaue="Virudhunagar">Virudhunagar</option>
<option vlaue="Visakhapatnam">Visakhapatnam</option>
<option vlaue="Vizianagaram">Vizianagaram</option>
<option vlaue="Vyara">Vyara</option>
<option vlaue="Warangal">Warangal</option>
<option vlaue="Wardha">Wardha</option>
<option vlaue="Washim">Washim</option>
<option vlaue="Wayanad">Wayanad</option>
<option vlaue="WestChamparan">West Champaran</option>
<option vlaue="WestDelhi">West Delhi</option>
<option vlaue="WestGaro Hills">West Garo Hills</option>
<option vlaue="WestKameng">West Kameng</option>
<option vlaue="WestKhasiHills">West Khasi Hills</option>
<option vlaue="WestSiang">West Siang</option>
<option vlaue="WestSikkim">West Sikkim</option>
<option vlaue="WestSinghbhum">West Singhbhum</option>
<option vlaue="WestTripura">West Tripura</option>
<option vlaue="Wokha">Wokha</option>
<option vlaue="Yadgir">Yadgir</option>
<option vlaue="YamunaNagar">Yamuna Nagar</option>
<option vlaue="Yanam">Yanam</option>
<option vlaue="Yavatmal">Yavatmal</option>
<option vlaue="Zunheboto">Zunheboto</option>